[package]
name = "declarative_alpine_manager"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2.0.12"
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
regex = "1.10"
