packages = [
  "openssl",
  "doas",
  "linux-lts",
  "alpine-base",
  "busybox-mdev-openrc",
  "e2fsprogs",
  "linux-firmware-none",
  "syslinux",

  "git",
  "vim",
  "openssh"
]

# [[users]]
# name = "tayler"
# shell = "/bin/ash"
# groups = ["wheel"]

# [services]
# sshd = { enabled = true, running = true }

# [networking.interfaces]
# eth0 = { ip = "192.168.1.10/24" }
